### ISSUE TITLE
I would like to play mp4 video using memory stream

### ISSUE THREAD

**Issue by sameerdube9** [CryShana/CryMedia#1]
I have encrypted video which I would like to play chunk by chunk using memory stream

can this be possible with VideoPlayer component?

request if you can make that way, at least play from memory stream

**Comment by CryShana** [comment]
This should be possible using the `VideoPlayer.GetStreamForWriting` method.

Example when using VideoReader:
```cs
// open player stream - specify format, resolution, framerate and pixel format
var playerStream = VideoPlayer.GetStreamForWriting("rawvideo", 
    $"-video_size {width}:{height} -framerate {framerate} -pixel_format rgb24",
    out Process playerProcess);

// copy from stream to player stream
video.DataStream.CopyTo(playerStream);

```

You can use any stream for this, just make sure the FFplay parameters are correct! Make sure to specify the correct video format, resolution, framerate and pixel format. Framerate should be given in format "60/1" for 60fps etc...

**Comment by sameerdube9** [comment]
Thank you, very much for your answer
