### ISSUE TITLE
subscribing to event ErrorDataReceived does not allow to update UI, kindly suggest

### ISSUE THREAD

**Issue by sameerdube9** [CryShana/CryMedia#10]
p.ErrorDataReceived += (sender, d) =>
{
    if (!string.IsNullOrEmpty(d.Data))
    {
        Match match = Regex.Match(d.Data, pattern);
        if (match.Success)
        {
            string number = match.Groups[1].Value;
            int progress = Convert.ToInt32(number);
            FileDto.EncryptionPercentage = progress * 100 / totalChunks;
            Dispatcher.InvokeAsync((Action)delegate
            {
                TranscodeProgressBar.Value = FileDto.EncryptionPercentage.Value;
                //if (OnFileEncryptProgressChanged != null)
                //    OnFileEncryptProgressChanged?.Invoke(new EncryptEventArgs(fileDto));
            });
            //TranscodeProgressBar.Value = FileDto.EncryptionPercentage.Value;
            //if (OnFileEncryptProgressChanged != null)
            //    OnFileEncryptProgressChanged?.Invoke(new EncryptEventArgs(fileDto));
        }
    }

**Comment by CryShana** [comment]
You are going to have to provide me more information. 

The `ErrorDataReceived` is an event like any other and can be invoked on a different thread than the UI thread. This means you would have to invoke any UI changes on the UI thread either using the `SynchronizationContext` manually or the `Dispatcher` (which *should* be a wrapper around it) and you are already using it, which is good.

You could also make sure `FileDto.EncryptionPercentage` property is not being binded anywhere in the UI - if it is, you would need to move it inside the Dispatcher call too. But other than that it looks fine.

If it still doesn't work, I would need to know the exact error you are getting

**Comment by sameerdube9** [comment]
p.EnableRaisingEvents = true;
// wait for all processes to finish
await p.WaitForExitAsync();

I have enabled this and solved the problem
