### ISSUE TITLE
Invalid duration specification for ss:30 (ffmpeg)

### ISSUE THREAD

**Issue by j0nat** [CryShana/CryMedia#2]
Hi

I got this error when using Load(30):
`Invalid duration specification for ss: 30,00`

Resolved by adding CultureInfo:

public void Load(double offsetSeconds)
{
       **CultureInfo enUS = new CultureInfo("en-US");**
       // we will be reading video in RGB24 format
       DataStream = FFmpegWrapper.OpenOutput(ffmpeg, $"{(offsetSeconds <= 0 ? "" : $"-ss {**offsetSeconds.ToString(enUS)**:0.00}")} -i \"{Filename}\"" +
$" -pix_fmt rgb24 -f rawvideo -");
       OpenedForReading = true;
}

**Comment by CryShana** [comment]
Thanks for noticing. It seems I forgot to make it culture invariant. I have now fixed it and expect a new release soon

**Comment by CryShana** [comment]
I have now released v1.0.9 that should include this fix. Please check it out.
