### ISSUE TITLE
Can I use this redo to download m3u8 live stream URL and save to local hard drive.

### ISSUE THREAD

**Issue by zydjohnHotmail** [CryShana/CryMedia#4]
Hello:
I happen to find your repo, and it seems to be interesting. However, as it is rather complicated, 
I can’t figure out yet how to download multiple M3U8 videos and save to local hard drive.
For example, I have the following 2 M3U8 videos in the URL:
http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
I want to launch 2 clients to download them at the same time, when finished, I want to save the files as local files: C:\1.mp4 and C:\2.mp4 and stop or dispose the client.
Please show me how I can do this with C#.
By the way, I am using Windows 10 Version 21H1, and Visual Studio 2019 Version 16.10.4.
Thanks,

**Comment by CryShana** [comment]
FFmpeg can parse M3U8 files, so you could just pass the m3u8 link directly to FFmpeg.

Something like this:
```cs
using System;
using CryMediaAPI;
using System.Collections.Generic;

var links = new List<string> {
    "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8",
    "http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8"
};

int fileCounter = 0;
foreach (var l in links)
{
    var output_file = $"video_{fileCounter++}.mp4";

    var process = FFmpegWrapper.ExecuteCommand("ffmpeg", $"-i \"{l}\" -c copy {output_file}");

    process.WaitForExit();

    Console.WriteLine($"Downloaded video from '{l}' --> {output_file}");
}
```

This will run FFmpeg for every link and save it to file `video_0.mp4` and then `video_1.mp4` and so on...

To avoid transcoding, I just used the flag `-c copy` to copy all the content. Sometimes you may also want to transcode it. If you want H.264, you could just replace it with `-c:v libx264`  (the audio is converted automatically as well)

If you want to run multiple clients at the same time, you could easily paralize this. Or just take away the `Process.WaitForExit()` and first start all the FFmpegs - and later wait for all of them.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I have tested with the links, and they worked.
However, I need other code samples for parallel clients.
For example, I have the following 2 live streaming URL for Olympic games, which is underway at the same time, which will be finished within one hour time.
            var links = new List<string> {
                "https://video.maxline.by:444/n1/stream61/chunks.m3u8?nimblesessionid=4798699",
                "https://video1.maxline.by:444/o1/stream09/chunks.m3u8?nimblesessionid=3015537" };
I have to download the both URL at the same time.
Your code above now only download the first, and after the first is done, continue the second.
Please advise!
Thanks,

**Comment by CryShana** [comment]
Either create separate threads, or tasks ...

But I think the easiest way with the existing code is to just replace the foreach loop with `Parallel.ForEach` and limit number of parallelism with `ParallelOptions` like this:
```cs
// add these to the existing usings
using System.Threading.Tasks;
using System.Threading;

int fileCounter = 0;
Parallel.ForEach(links, new ParallelOptions
{
    // we want max. 2 clients running in parallel
    MaxDegreeOfParallelism = 2
}, l =>
{
    var fileCount = Interlocked.Increment(ref fileCounter);

    var output_file = $"video_{fileCount}.mp4";
    var process = FFmpegWrapper.ExecuteCommand("ffmpeg", $"-i \"{l}\" -c copy {output_file}");

    process.WaitForExit();

    Console.WriteLine($"Downloaded video from '{l}' --> {output_file}");
});
``` 

**OR** you could also store all processes and wait for them to exit like this:
```cs
// add this to existing usings
using System.Diagnostics;

var processes = new List<Process>();

int fileCounter = 0;
foreach (var l in links)
{
    var output_file = $"video_{fileCounter++}.mp4";
    var process = FFmpegWrapper.ExecuteCommand("ffmpeg", $"-i \"{l}\" -c copy {output_file}");

    processes.Add(process);
}

// wait for all processes to finish
foreach (var p in processes) p.WaitForExit();
```
