### ISSUE TITLE
Can i use this library to achieve .mp4 to hls

### ISSUE THREAD

**Issue by sameerdube9** [CryShana/CryMedia#5]
Hello @CryShana ,

I would like to convert .mp4 to hls format, reference given below, Please guide if I could convert .mp4 to hls with this library

**reference:**
https://www.codeproject.com/Articles/3144032/HTTP-Live-Streaming-HLS-VOD

**Comment by CryShana** [comment]
For more fine-grained control over FFmpeg, use the `FFmpegWrapper` class directly and pass the the whole command to it.

Below is an example for only 1080p transcoding: (I just copied the command for 1080p from the referenced website)
```cs
var inputVideo = "input.mp4";
var namePrefix = "output";

// start process for 1080p transcoding 
var p = FFmpegWrapper.ExecuteCommand("ffmpeg",
    $"-i \"{inputVideo}\" -vf scale=w=1920:h=1080:force_original_aspect_ratio=decrease " +
    $"-c:a aac -ar 48000 -c:v h264 -profile:v main -crf 20 -sc_threshold 0 -g 48 " +
    $"-keyint_min 48 -hls_time 4 -hls_playlist_type vod -b:v 5000k -maxrate 5350k " +
    $"-bufsize 7500k -b:a 192k -hls_segment_filename {namePrefix}_1080p_%d.ts {namePrefix}_1080p.m3u8");

// wait for all processes to finish
p.WaitForExit();
```

You can then easily concatenate multiple transcoding commands and pass them to FFmpeg. 
Or run each transcoding as a separate process.

**Comment by sameerdube9** [comment]
can we have any event which can show the progress from 0% to 100%, how the transcoding will happen

**Comment by sameerdube9** [comment]
I have used following code but progress tracking not working
 //Process
 var p = FFmpegWrapper.ExecuteCommand("ffmpeg", conversionArgs);
  
 var progress = FFmpegWrapper.RegisterProgressTracker(p, 91);
 progress.ProgressChanged += Progress_ProgressChanged;
 Debug.WriteLine( isProcessing = IsProcessRunning("ffmpeg"));
 // wait for all processes to finish
