### ISSUE TITLE
Record stream to mp4

### ISSUE THREAD

**Issue by Haxnaat** [CryShana/CryMedia#6]
Is this wrapper has functionlity to record live stream into chunks of mp4?

**Comment by CryShana** [comment]
You will have to use the **FFmpegWrapper** class for this.

Assuming you want segments about 60 seconds in length - and they will not be re-encoded. Usage would look like this:
```cs
var process = FFmpegWrapper.ExecuteCommand("ffmpeg",
    "-i rtsp://some_stream_url " +
    "-c copy -f segment -segment_time 60 -reset_timestamps 1 segment_%03d.mp4", true);

process.WaitForExit();
```
(This command will also write to console automatically)

Segments will be named like "segment_000.mp4", "segment_001.mp4" and so on.

If you want to parse the progress  yourself, you can leave out the last `true` argument - and handle output yourself like so:
```cs
// var process = ExecuteCommand(...)

process.ErrorDataReceived += (a, b) =>
{
    Console.WriteLine(b.Data);
};

process.WaitForExit();
```
