### ISSUE TITLE
issue with ProgressTracker

### ISSUE THREAD

**Issue by sameerdube9** [CryShana/CryMedia#9]
https://github.com/CryShana/CryMedia/issues/5

**Comment by CryShana** [comment]
I am using `ffmpeg version n6.1.1-20240102` and `CryMedia 1.2.0` from 2022, I used the following code:

```cs
var p = FFmpegWrapper.ExecuteCommand("ffmpeg", $"""-i "{filename}" output.mp4""");

var progress = FFmpegWrapper.RegisterProgressTracker(p, 40);

progress.ProgressChanged += (sender, progress) => {
    Console.WriteLine("Progress: " + progress);
};

p.WaitForExit();
```

I successfully got the following output:
```
Progress: 1.0999999999999999
Progress: 11.725000000000001
Progress: 22.749999999999996
Progress: 29.049999999999997
Progress: 34.975
Progress: 40.9
Progress: 48.1
Progress: 55.99999999999999
Progress: 64.57499999999999
Progress: 73
Progress: 81.89999999999999
Progress: 89.7
Progress: 97.65
Progress: 100
```
So it still works for ffmpeg 6.1 build from 2.Jan 2024.

Which version of `ffmpeg` are you using? Do your arguments contain anything that would affect the output? Process is most likely not outputting the expected format. In case that happens, you can also parse the process output yourself.

---

I am aware the library is a bit outdated, but the same code can still be used and adjusted for your use case. If you check the method `RegisterProgressTracker`, it simply subscribes to `ErrorDataReceived` on the process, and then uses Regex to parse the processed duration. 

If for any reason your ffmpeg process is not outputting this duration, it will not be able to get the progress. I would suggest you try debugging this by tracking everything the ffmpeg process is outputting. And maybe implementing your own parsing method of this duration in case you have a different one.
